name: secrets-vars

on: push
env:
  USER_NAME: SAM
  PASSWORD: password@123

jobs:
  test-secrets-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print Variable
        run: echo $USER_NAME

      - name: Print Secret
        run: echo $PASSWORD